### ISSUE TITLE
Whole app is broken and left in the dust

### ISSUE THREAD

**Issue by WuXu1** [n3d1117/appdb#101]
Sad to see such a good app be left. All the new features appdb are releasing are clearly too much for this dev, he can’t keep up with the updates and fails to even fix the bugs that stop us from using the main features of the app completely. The “installation options feature” prompt barely even functions - injecting dylibs is broken, the duplicate app code gets mixed up with changing the app name, you can’t import and upload ipa’s to myappstore like you used to, and now you can’t even install apps from there either. This is on top of the number of unresolved issues on github.

I’d suggest handing this app over to someone at appdb, they will know how to actually maintain it and give us frequent useful updates.

**Comment by n3d1117** [comment]
Hi @WuXu1, I understand your point. Sadly I no longer have time to maintain this app, which is why the last couple of releases are done by @stev3fvcks. 
If anyone else wants to contribute, do let me know and I'll add them as a collaborator.
