### ISSUE TITLE
iOS 13.1.3 - open in Appdb - not working

### ISSUE THREAD

**Issue by MrL0** [n3d1117/appdb#37]
Hi - On iOS 12.4 I was able to download an ipa and import to Appdb app via “open in”, but now on iOS 13.1.3 it doesn’t import to local files. I’m I missing something or is this a know issue?

**Comment by n3d1117** [comment]
Hello, thanks for your report. Sadly I'm not able to reproduce the issue (I am on 12.4 still), but I will look into it as soon as I get an iOS 13 device!

**Comment by n3d1117** [comment]
Hello @MrL0 could you test [this build](https://github.com/n3d1117/appdb/files/3791059/appdb_dwuhe8273.ipa.zip) and see if the issue is fixed? Thanks

**Comment by MrL0** [comment]
> Hello @MrL0 could you test [this build](https://github.com/n3d1117/appdb/files/3791059/appdb_dwuhe8273.ipa.zip) and see if the issue is fixed? Thanks

No go. It still doesn’t copy the ipa to local. With iOS 13 downloads feature, it downloads to the files app. When selecting the IPA, it only shows “Open in Appdb” but not a “Copy to Appdb” in the shared sheet. I moved the IPA to my Dropbox and from there the option “Copy to” was available but not in files app.

**Comment by n3d1117** [comment]
This is weird, it's working fine on my device even for 'Open in ...' options. Will look more into it.

**Comment by n3d1117** [comment]
@MrL0 It looks like iOS 13 prevents files to be opened in an app that was resigned (via impactor/appdb/etc..). Here are some workarounds:
- Build app yourself with Xcode, it will work
- Use Files app to move downloaded .ipa files directly into appdb folder, it should work too (appdb will detect .ipa automatically)
- Use Telegram/Chrome share sheet and select "Copy to appdb"

**Comment by MrL0** [comment]
> @MrL0 It looks like iOS 13 prevents files to be opened in an app that was resigned (via impactor/appdb/etc..). Here are some workarounds:
> 
> * Build app yourself with Xcode, it will work
> * Use Files app to move downloaded .ipa files directly into appdb folder, it should work too (appdb will detect .ipa automatically)
> * Use Telegram/Chrome share sheet and select "Copy to appdb"

Works in chrome. Thank you! I should’ve tried that sorry.
