### ISSUE TITLE
[REQ] Re-download all apps after revoke

### ISSUE THREAD

**Issue by adrianmihalko** [n3d1117/appdb#42]
Thanks for this great application. I miss a function, where after a revoke we should be able to resign all sideloaded apps at once. 

Currently, we must delete the app and download again. For each sideloaded app. My experience is, that It's not enough to re-download, and install over currently installed app, you must first delete the actual app. Very inconvenient.

My second request/suggestion is to add a "Update all" button on the Updates tab, like in the real appstore.

**Comment by n3d1117** [comment]
Hello, thanks for your feature request!
As you know on appdb every app has multiple links for download. How would you suggest choosing the right link to use when clicking update all / resign all?

**Comment by adrianmihalko** [comment]
I don't know AppDB's API (do we have info about verified links?), but we should simple do this by a trial&error and/or randomize (to not overload a link provider)?

**Comment by ZonD80** [comment]
It allows you to do it now (AFAIR), can you implement this (it's called IPA cache on appdb)

**Comment by n3d1117** [comment]
Added support for IPA Cache in [1.1.2](https://github.com/n3d1117/appdb/releases/tag/v1.1.2), closing this
