### ISSUE TITLE
Ipa files

### ISSUE THREAD

**Issue by rodainas** [n3d1117/appdb#48]
Hi thanks for the app is great

I have the device jailbroken, am using the jailbreak appsync option, when i choose to download an app it automatically download and install just like the appstore works, am looking for the ipa file downloaded but cant find anywhere on Filza, neither the app downloads section, is there a way to save/keep the ipa files of the downloaded apps using your client?

**Comment by n3d1117** [comment]
Hi, to save the ipa file you can click on links instead of green INSTALL buttons.
