### ISSUE TITLE
iPhone 12 Pro Max not working

### ISSUE THREAD

**Issue by forzabatur** [n3d1117/appdb#54]
Appdb client (this software) does not work on iPhone 12 Pro Max.
Is it possible to update it ?

**Comment by n3d1117** [comment]
Hi, what does not work? There shouldn't be any issue

**Comment by DarkIllusi0n** [comment]
I have an iPhone 12 Pro Max on iOS 14.4 and it's running fine.

**Comment by n3d1117** [comment]
@DarkIllusi0n thanks. Will be closing this for now.
