### ISSUE TITLE
carthage update --platform iOS error

### ISSUE THREAD

**Issue by gotzlotz** [n3d1117/appdb#56]
I get this error when I use carthage update --platform iOS.

Building scheme "Alamofire iOS" in Alamofire.xcworkspace
A shell task (/usr/bin/xcrun lipo -create /Users/marcus/Library/Caches/org.carthage.CarthageKit/DerivedData/12.4_12D4e/Alamofire/5.4.1/Build/Intermediates.noindex/ArchiveIntermediates/Alamofire\ iOS/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/Alamofire.framework/Alamofire /Users/marcus/Library/Caches/org.carthage.CarthageKit/DerivedData/12.4_12D4e/Alamofire/5.4.1/Build/Products/Release-iphonesimulator/Alamofire.framework/Alamofire -output /Users/marcus/Downloads/appdb-master/Carthage/Build/iOS/Alamofire.framework/Alamofire) failed with exit code 1:
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: /Users/marcus/Library/Caches/org.carthage.CarthageKit/DerivedData/12.4_12D4e/Alamofire/5.4.1/Build/Intermediates.noindex/ArchiveIntermediates/Alamofire iOS/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/Alamofire.framework/Alamofire and /Users/marcus/Library/Caches/org.carthage.CarthageKit/DerivedData/12.4_12D4e/Alamofire/5.4.1/Build/Products/Release-iphonesimulator/Alamofire.framework/Alamofire have the same architectures (arm64) and can't be in the same fat output file

Building universal frameworks with common architectures is not possible. The device and simulator slices for "Alamofire" both build for: arm64
Rebuild with --use-xcframeworks to create an xcframework bundle instead.

**Comment by n3d1117** [comment]
Hello, thanks for opening this issue!
In bf1479e7195ae083d012e11ac7411b72b838ba6a I have migrated from framework bundles to XCFrameworks.
Please pull latest commit, clean your `Carthage` folder and try rebuilding the project `carthage update --platform iOS --use-xcframeworks`. You'll also need latest [Carthage](https://github.com/Carthage/Carthage/releases) (v37.0 or later) installed.
I've also updated the README accordingly. Please let me know if it works so I can close this.

**Comment by gotzlotz** [comment]
Will try in a few. How do I clean my Carthage folder. 😅

**Comment by n3d1117** [comment]
> Will try in a few. How do I clean my Carthage folder. 😅

You can just delete it from Finder app! You should find it inside the project's folder

**Comment by gotzlotz** [comment]
Oh ok..got. Thanks
