### ISSUE TITLE
Cart Error on 1.1.1

### ISSUE THREAD

**Issue by gotzlotz** [n3d1117/appdb#61]
get this command error after entering "carthage update --platform iOS --use-xcframeworks"

Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/marcus/Downloads/appdb/Carthage/Checkouts/SwiftMessages/iMessageDemo/iMessageDemo.xcworkspace -scheme SwiftMessages -configuration Release -derivedDataPath /Users/marcus/Library/Caches/org.carthage.CarthageKit/DerivedData/13.0_13A5154h/SwiftMessages/9.0.2 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive VALIDATE_WORKSPACE=NO -archivePath /var/folders/v9/spyf71qn3vvg_lg6_xkb46_r0000gn/T/SwiftMessages SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/marcus/Downloads/appdb/Carthage/Checkouts/SwiftMessages)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/v9/spyf71qn3vvg_lg6_xkb46_r0000gn/T/carthage-xcodebuild.37su4c.log

The last few lines in the log file says this 

The following build commands failed:
	CompileSwift normal arm64 (in target 'SwiftMessages' from project 'Pods')
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'SwiftMessages' from project 'Pods')
	CompileSwiftSources normal armv7 com.apple.xcode.tools.swift.compiler (in target 'SwiftMessages' from project 'Pods')
	CompileSwift normal armv7 (in target 'SwiftMessages' from project 'Pods')
(4 failures)

**Comment by n3d1117** [comment]
Hi, I can't reproduce this. Just tested with a fresh carthage build and it worked fine.
Make sure you have latest Xcode installed (v12.5), latest Carthage (v0.38.0) and also try cleaning `Carthage` folder before running the command

**Comment by gotzlotz** [comment]
How do I clean my Carthage folder.

**Comment by n3d1117** [comment]
> How do I clean my Carthage folder.

You can just delete it, it rebuilds automatically

**Comment by gotzlotz** [comment]
Sorry, you know where is located 😅
