### ISSUE TITLE
[Feature Request] App Icon

### ISSUE THREAD

**Issue by stayxnegative** [n3d1117/appdb#62]
Can you implement a dark themed icon to be able to switch to? I created one already, if you’d like to use it. 

![10229FE9-4605-4487-8CC3-7C381D60735B](https://user-images.githubusercontent.com/29215335/129496356-94eb9dc7-1d40-4904-b242-4d3e391f44a6.jpeg)

**Comment by n3d1117** [comment]
Done in abeee5daa6069d990c807876e4c6f2f84059b8c8! Thanks, I've included yours and a few more :)
