### ISSUE TITLE
App no longer working. Requires update for API 1.4 as of January 2nd.

### ISSUE THREAD

**Issue by hbashton** [n3d1117/appdb#65]
Here is a screenshot of the current state of the app. Let the developer handle this soon, please :)
![7BBB210E-8C51-4B78-B320-26EA06395097](https://user-images.githubusercontent.com/12548996/148091363-15b73aad-ca59-4f6d-8824-53ed5721e7af.png)

**Comment by sshrmr** [comment]
++++++
same here

**Comment by QiuIcs** [comment]
Same

**Comment by iMonZ** [comment]
+1

**Comment by Am1nCmd** [comment]
Hi, I just checked the main update only to API v1.4 and already commit by itsmylife44,

wait ned to merge and compile it to an IPA

**Comment by n3d1117** [comment]
Fixed in [v1.1.2](https://github.com/n3d1117/appdb/releases/tag/v1.1.2), thanks y'all
