### ISSUE TITLE
UI issue in 1.1.3

### ISSUE THREAD

**Issue by c12n** [n3d1117/appdb#73]
![image](https://user-images.githubusercontent.com/96452263/160096491-b9b85cd7-ad06-47ce-8885-54bd568b60fc.jpeg)

Is this how it should be

 ![image](https://user-images.githubusercontent.com/96452263/160096543-16513b79-9e81-4013-925b-02710a962258.jpeg)

**Comment by n3d1117** [comment]
Hi @c12n, that's odd, that UI is provided by Apple. Does the icon actually change tho?

**Comment by n3d1117** [comment]
Gonna close this for now since I have no control over that alert
