### ISSUE TITLE
Show download numbers on the app

### ISSUE THREAD

**Issue by c12n** [n3d1117/appdb#74]
If the API allows it, show download numbers. This would be useful for uploaders.

**Comment by n3d1117** [comment]
AFAIK appdb APIs don't have download numbers. You can request it here: https://forum.appdb.to/index.php?/forum/41-appdb-api/

I'll keep this open in case there are further updates

**Comment by stev3fvcks** [comment]
Hi, I added them. (Commit [17a33c9](https://github.com/n3d1117/appdb/commit/17a33c9c8561767be3da1a8a1094aa298a518084))

Available in the latest release [1.1.5](https://github.com/n3d1117/appdb/releases/tag/v1.1.5)
