### ISSUE TITLE
[Feature Request] Add ability to post and view comments.

### ISSUE THREAD

**Issue by yodaluca23** [n3d1117/appdb#81]
Please add the ability to post and view comments. Maybe with some sort of in-app Disqus account linking...

**Comment by stev3fvcks** [comment]
Please use the share button to get to the appdb website for the specific app, if you want to check and posts comments on Disqus.

**Comment by stev3fvcks** [comment]
Please use the share button to get to the appdb website for the specific app, if you want to check and posts comments on Disqus.

**Comment by stev3fvcks** [comment]
Please use the share button to get to the appdb website for the specific app, if you want to check and posts comments on Disqus.
