### ISSUE TITLE
[Feature Request] Add a true Black icon option!

### ISSUE THREAD

**Issue by CortezJEL** [n3d1117/appdb#82]
If you use this version i desire no credit!
<img src="https://i.imgur.com/p2Xfrqd.png">
https://i.imgur.com/p2Xfrqd.png

**Comment by stev3fvcks** [comment]
Hi, I added it. (Commit [63589ba](https://github.com/n3d1117/appdb/commit/63589ba1cff1d3c9fdc2527b6706d57a0dbeace6))

Available in the latest release [1.1.5](https://github.com/n3d1117/appdb/releases/tag/v1.1.5)
