### ISSUE TITLE
Update for new Installation Options

### ISSUE THREAD

**Issue by WuXu1** [n3d1117/appdb#84]
Hello, In the recent appdb update, you can now upload and inject your own dylibs, frameworks or debs. Can this be added to the client?

I'm hoping the project hasn't been abandoned as it was last edited a year ago.

Anyway, loving it so far.

**Comment by stev3fvcks** [comment]
Hi, it was added in [v1.1.4](https://github.com/n3d1117/appdb/releases/tag/v1.1.4) :)
