### ISSUE TITLE
AppDB API Update

### ISSUE THREAD

**Issue by Kief5555** [n3d1117/appdb#87]
AppDB updated their api. The app does not support it and is currently having issues with V1.5

News: https://appdb.to/news/495
Docs: https://api.dbservices.to/v1.6/spec/
Migration: https://telegra.ph/API-v15-to-v16-migration-guide-05-17

Current issues include
- Download links/install
- Updates
- Developer name

Another thing that needs to be address is the building steps.
 

Multiple devs have attempted when building frameworks with multiple issues regarding the main framework during build process

**Comment by Freddelloyd** [comment]
Any progress? @stev3fvcks

**Comment by Freddelloyd** [comment]
> Any progress? @stev3fvcks 

@stev3fvcks @n3d1117

**Comment by edsonbittencourt** [comment]
Please, guys, this is the best way to use appdb!

**Comment by nammminn2** [comment]
so no update yet :(

**Comment by n3d1117** [comment]
@nammminn2 https://github.com/n3d1117/appdb/pull/92 :)

**Comment by n3d1117** [comment]
Hey everyone, good news, i took the day off and finally added support for v1.6 APIs in #92!
@stev3fvcks will do a few fixes and polish a new release soon!

**Comment by edsonbittencourt** [comment]
Whohooooooo!

**Comment by vegetax58** [comment]
Can't wait. Thank you

**Comment by c12n** [comment]
Update ?

**Comment by Purplerain18** [comment]
> Hey everyone, good news, i took the day off and finally added support for v1.6 APIs in #92! @stev3fvcks will do a few fixes and polish a new release soon!

This was two weeks ago can someone define soon for me please lol

**Comment by stev3fvcks** [comment]
Finally done. Check [v1.1.6](https://github.com/n3d1117/appdb/releases/tag/v1.1.6)

**Comment by edsonbittencourt** [comment]
Thank you so much, thank you for your effort.

**Comment by Kief5555** [comment]
![image](https://github.com/n3d1117/appdb/assets/67562560/299ef247-f85b-4052-a59f-815de1da7735)

Is it possible to include these options too?
