### ISSUE TITLE
New api

### ISSUE THREAD

**Issue by Freddelloyd** [n3d1117/appdb#88]
Please update the app to support the new api

**Comment by Freddelloyd** [comment]
@stev3fvcks @n3d1117 Please it would make everyone very happy

**Comment by Isntreallyme23** [comment]
Please Please update the app to support the new api 👍

**Comment by n3d1117** [comment]
Closing as duplicate of #87. @stev3fvcks (who now maintains this app) is aware of the API changes and will work on an update asap

**Comment by Freddelloyd** [comment]
Thank you bro
