### ISSUE TITLE
Add direct download links

### ISSUE THREAD

**Issue by Hikiru** [n3d1117/appdb#96]
Show a link for the ipa downloads so you don’t have to click share, open the appdb.to page in safari, then click the link from there. I use appdb to find ipa’s to sideload with scarlet once I’ve reached appdb’s app limit

**Comment by TOPBIMAN** [comment]
The

**Comment by stev3fvcks** [comment]
Just click the cell instead of the INSTALL button and it will open the url in a in-app browser that can be used to share the link but also to download the file to the local library, too.
